import Head from "next/head";
import Navbar from "../components/Navbar";
import HomeSection from "../components/BackgroundImage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mead Orchards Offseason</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <HomeSection        
        bgImage="/meadsnow.jpg"
        heading="OFFSEASON"
        height="80vh"
        headingSize="6rem"
        subheadingSize="3rem"
        imagePosition="center center"
      />
      </>
      );
}