import Head from "next/head";
import Navbar from "../components/Navbar";
import HomeSection from "../components/LandingPage";
import HomeSection2 from "../components/Newsletter";
import Hours from "../components/FruitsVeggies";
import Hours2 from "../components/OrchardHours";
import InstagramPage from "../components/Instagram";
import Footer from "../components/Footer";
import AnimatedTitle from "../components/typewriter";
export default function Home() {
  return (
    <>
      <Head>
        <title>Mead Orchards: Hudson Valley's Original Pick Your Own Farm</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      

      <HomeSection
        bgImage="/MeadHomePageImage.jpg"
        subheading1="Pick Your Own. The Way It Used To Be."
        subheading2="Since 1916."
        height="110vh"
        headingSize="6rem"
        subheadingSize="2.5rem"
        imagePosition="center top"
        logoImage="/MeadLogo.png"
        showLogo={true}
      />
      <Hours />
      <Hours2 />
      <HomeSection2
        bgImage="/applepicking.jpg"
        subheading1="Keep Up With the Latest Farm News, Fruit Availability, Special Offers, Rewards, Events, and More!"
        height="80vh"
        headingSize="3rem"
        subheadingSize="2rem"
        imagePosition="center center"
        showButton={true}
      />
< br />
      <InstagramPage />
      < br/>
      <Footer />

    </>
  );
}



