import Head from "next/head";
import Navbar from "../components/Navbar";
import HomeSection from "../components/BackgroundImage";
import Hours from "../components/HomePage";
import InstagramPage from "../components/Instagram";
import Footer from "../components/Footer";
import SignUpForm from "../components/SignUpPopup";

export default function Home() {
  return (
    <>
      <Head>
        <title>Mead Orchards: Hudson Valley's Original Pick Your Own Farm</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      
      <HomeSection
        bgImage="/MeadHomePageImage.jpg"
        heading="MEAD ORCHARDS"
        subheading1="Pick Your Ownasd. The Way It Used To Be."
        subheading2="Since 1916."
        height="115vh"
        headingSize="6rem"
        subheadingSize="2.5rem"
        imagePosition="center top"
        logoImage="/MeadLogo.png"
        showLogo={true}
      />

      <Hours />

      <HomeSection
        bgImage="/applepicking.jpg"
        heading="Sign Up For Our Newsletter"
        subheading1="Keep Up With the Latest Farm News, Fruit Availability, Special Offers, Rewards, Events, and More!"
        height="80vh"
        headingSize="3rem"
        subheadingSize="2rem"
        imagePosition="center center"
        showButton={true}
      />
< br />
      <InstagramPage />
      < br/>
      <Footer />

    </>
  );
}



